### ISSUE TITLE
Day/Night in Automatic mode

### ISSUE THREAD

**Issue by qutschwalze** [dewenni/ESP_Buderus_KM271#1]
Hi!
Sorry for the question but how can I see that the heating system is in the Day (Tag) or Night (Nacht) mode when it is running in the normal Automatic mode? 

Many thanks!

**Comment by dewenni** [comment]
Hi,
thanks for the question. You can get the information from "HK1_BW2_Tag"

HK1_BW2_Tag = 0 => Nacht
HK1_BW2_Tag = 1 => Tag

same as "HK1_BW2_Sommer"

HK1_BW2_Sommer = 0 => Winter
HK1_BW2_Sommer = 1 => Sommer

![image](https://user-images.githubusercontent.com/46074831/205620517-a69a1f83-df18-486e-9acf-93c53c7eb1b0.png)
