### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by stefangrosse** [dewenni/ESP_Buderus_KM271#100]
Hallo.
Ich habe mir das Board bestellt über den Link hier, bekomme es aber nicht zum Laufen. Muss ich das Board noch flashen oder ist das bereits ready to use? Wenn ich die Reset-Taste zweimal in drei Sekunden drücke, taucht kein WLAN auf, damit ich mit dem Board verbinden kann.
Das Board blinkt immer grün. Was mache ich falsch? Ich finde keine Anleitung.
Vielen Dank

**Comment by dewenni** [comment]
Hi,

Normalerweise flashed Daniel das Board vor Auslieferung mit der Software die bei der Bestellung ausgewählt wird.
Die b und was bei dir jetzt drauf ist, kann ich leider nicht sagen.

Hast du einen USB-Serial Adapter zum Flashen? Würde ich dir so oder so empfehlen.
Dann kannst du dir Software selbst aufspielen.
Anleitung ist auf meiner GitHub Startseite.

**Comment by stefangrosse** [comment]
Da ist ESPHome drauf. Laut Lieferschein. Da habe ich dann nicht aufgepasst. Serial to USB habe ich, da ich auch das Originalmodul von Buderus habe. Ich probiere mich dann mal ans flashen. Danke für Deine schnelle Rückmeldung!

**Comment by the78mole** [comment]
Hallo Stefan,

Vorsicht! kein USB-RS232-Adapter wie bei der original KM271 sondern ein USB-UART-Adapter. Gleiches Protokoll, aber völlig andere Spannungspegel. RS232 hat positive und negative Spannungslevel bis zu 15V. TTL sind entweder 0/3,3V (das würde passen) oder 0/5V (das wäre zu viel).

Grüße,
Daniel

**Comment by the78mole** [comment]
Übrigens, eine "Anleitung" gibt es auch in Video-Form von mir: https://www.youtube.com/watch?v=h_pQlpXaQ1I&t=810s

**Comment by dewenni** [comment]
@stefangrosse hat es funktioniert?

**Comment by stefangrosse** [comment]
Ich muss mir erst ein Kabel besorgen. An dem Board ist ja auch ein Minisusbanschluß, der ist für externen Strom, nehme ich an. Melde mich wieder

**Comment by dewenni** [comment]
@stefangrosse 
ja, über den Mini-USB kannst du das Board extern mit Spannung versorgen. Bei manchen Buderus Logamatic ist die intern Spannungsversorgung für das Board scheinbar etwas knapp.

Bezüglich Kabel/Adapter - diese hier sollten funktionieren:
[Modell 1](https://www.amazon.de/UART-TTL-Adapter-Konverter-Jumperkabel-kompatibel/dp/B0B7RHPMT7/ref=sr_1_3?__mk_de_DE=ÅMÅŽÕÑ&crid=1FLJ527KVK3BW&dib=eyJ2IjoiMSJ9.hAH0rE1YoY6Rx6GQQn5eWr9xIcJ2MogHPSLtkzbsBP1NfUrYQV0xoUOiVubZytndyz2HPg_0boc1Bba6MLOTQjA1htiHDeUyHU0nHv8T3tqx5DJyg7ICbhlpdzj1zJO6yqnw7E7noZGrqEU6vPbCO3ID3nvBd5ti1dMZDZn0Nyop-czvcTtBaoN0haoU_KQKA5WXtHFSF3WU2_AKl-952GUEMY3lM75jdxxq5Eyjtjc.P-wi2_FjpOzMwswjmsIFK2Yqst-MJ5y2k4scP8LKp28&dib_tag=se&keywords=usb+ttl&qid=1714068672&sprefix=usb+ttl%2Caps%2C97&sr=8-3)

[Modell 2](https://www.amazon.de/AZDelivery-Konverter-kompatibel-Arduino-inklusive/dp/B089QJZ51Z/ref=sr_1_30?__mk_de_DE=ÅMÅŽÕÑ&crid=18SO7D2MIHB39&dib=eyJ2IjoiMSJ9.ucrW6gxS9pJPbY8JOcXEJpB63K8p3tzKhqAGRxIwiIIfTg8k8zniF0XNWe4lJTp_IiMv0_32GrOSthoav2bNxGEhut7mcjV05O5CdIhKnEhN5DNhxASwvI2hXWryiW4Tkq7L1eXe3Au8kaCJYul36C7ZV2CQZ05B5eWW6dvbbOJpde8-eh39kBG0NJwoMb-b.KNZSrqlOTTOtiauB3KzIET38Zhw2bnhexmr7YmRu0cM&dib_tag=se&keywords=esp+adapter&qid=1714068630&sprefix=esp+adapte%2Caps%2C102&sr=8-30)

[Modell 3](https://www.amazon.de/AZDelivery-UART-TTL-Konverter-Jumperkabel-inklusive/dp/B08T24NML9/ref=sr_1_4?__mk_de_DE=ÅMÅŽÕÑ&crid=1FLJ527KVK3BW&dib=eyJ2IjoiMSJ9.hAH0rE1YoY6Rx6GQQn5eWr9xIcJ2MogHPSLtkzbsBP1NfUrYQV0xoUOiVubZytndyz2HPg_0boc1Bba6MLOTQjA1htiHDeUyHU0nHv8T3tqx5DJyg7ICbhlpdzj1zJO6yqnw7E7noZGrqEU6vPbCO3ID3nvBd5ti1dMZDZn0Nyop-czvcTtBaoN0haoU_KQKA5WXtHFSF3WU2_AKl-952GUEMY3lM75jdxxq5Eyjtjc.P-wi2_FjpOzMwswjmsIFK2Yqst-MJ5y2k4scP8LKp28&dib_tag=se&keywords=usb+ttl&qid=1714068672&sprefix=usb+ttl%2Caps%2C97&sr=8-4)

**Comment by the78mole** [comment]
@stefangrosse aber nicht vergessen, den PWR_SEL-Jumper umzusetzen, sonst bringt die USB-Versorgung nichts... (siehe Videoanleitung)

**Comment by stefangrosse** [comment]
Model 1 ist heute angekommen. Den Jumper auf dem Model 1 habe ich auf 3V geändert. Müssen einzelnen Kabel noch besonders angeklemmt werden, oder ist das egal!

**Comment by dewenni** [comment]
Am Ende musst du halt oben an die Anschlüsse für:  
- 3,3V
- GND
- TX
- RX

Am besten ist es, dort den Pin-Header anzulöten. Da kannst du dann die Kabel aufstecken.
Ansonsten müsstest du probieren die Kabel dort so irgendwie ranzuhalten. Das dürfte aber schwierig werden.

**Comment by stefangrosse** [comment]
Kannst Du mir einen Link für die richtigen Pin-Header geben? Dann bestelle ich die und versuche mich im löten.

**Comment by dewenni** [comment]
https://www.reichelt.de/stiftleisten-2-54-mm-2x03-gewinkelt-mpe-088-2-006-p119904.html

**Comment by stefangrosse** [comment]
So, ich habe es gelötet :-) Bekomme aber folgende Fehler-Meldung:

ls /dev/tty* | grep usb                                                                   
/dev/tty.usbserial-1130
esptool.py -p /dev/tty.usbserial-1130 write_flash 0x00 buderus_km271_esp32_flash_v4.1.0.bin
esptool.py v4.7.0
Serial port /dev/tty.usbserial-1130
Connecting......................................

A fatal error occurred: Failed to connect to Espressif device: No serial data received.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html

Hast Du eine Idee?

**Comment by dewenni** [comment]
Wenn ich es richtig sehe, hast du TX<>RX nicht gekreuzt?!

Also du musst TX > RX und RX > TX anschließen.

**Comment by dewenni** [comment]
Und wenn er in "connecting..." steht, BOOT gedrückt halten und dann Reset drücken.

**Comment by stefangrosse** [comment]
Ok. Am Board TX und am Usb RX oder andersrum? Sorry und danke für die super Unterstützung!

**Comment by stefangrosse** [comment]
Habe ich so gemacht, aber neue Meldung:

stefangrosse@MB-Pro Downloads % esptool.py -p /dev/tty.usbserial-120 write_flash 0x00 buderus_km271_esp32_flash_v4.1.0.bin
esptool.py v4.7.0
Serial port /dev/tty.usbserial-120
Connecting......................................

A fatal error occurred: Failed to connect to Espressif device: Invalid head of packet (0x42): Possible serial noise or corruption.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html

**Comment by stefangrosse** [comment]
Hat geklappt :-)
<img width="860" alt="image" src="https://github.com/dewenni/ESP_Buderus_KM271/assets/16479653/93ce3eb6-6832-414d-b3dd-351b60a43bb4">

**Comment by dewenni** [comment]
prima, läuft die Applikation jetzt auch?

**Comment by the78mole** [comment]
Hm, scheint funktioniert zu haben 🤣

**Comment by stefangrosse** [comment]
Moin. Bin jetzt erst wieder dazu gekommen. Den Setupmode konnte ich starten und mein wlan einrichten. Es kommen allerdings keine oder falsche Werte an. Die Heizung steht auf Sommer und nicht Winter. 
![image](https://github.com/dewenni/ESP_Buderus_KM271/assets/16479653/f9f92ccb-9fbc-4354-aeb3-f11564bb8f89)
![image](https://github.com/dewenni/ESP_Buderus_KM271/assets/16479653/a183ef08-f938-42b1-8d02-0e682004a5eb)
![image](https://github.com/dewenni/ESP_Buderus_KM271/assets/16479653/1462f0fe-c6c2-49c8-889a-8b50eabdb16d)
Den MQTT habe ich auch aktiviert und mit den LoginDaten aus Homeassistent versehen. Klappt bisher auch nicht.
Habe ich noch was vergessen?

**Comment by dewenni** [comment]
Hast du in den Einstellungen die GPIO´s eingestellt?

![image](https://github.com/dewenni/ESP_Buderus_KM271/assets/46074831/b645dd01-8275-4397-b29e-5bcd9c9791c5)

**Comment by stefangrosse** [comment]
Ne, konnte ich jetzt auch nicht mehr, da die Karte keine Verbindung mehr zum Wlan aufbaut.

**Comment by stefangrosse** [comment]
Ich habe die Karte erneut geflasht nun leuchten keine LEDs mehr. Ich kann das flashen beliebig oft wiederholen, aber die Karte leuchtet nicht mehr. Was kann ich tun?

<img width="1036" alt="image" src="https://github.com/dewenni/ESP_Buderus_KM271/assets/16479653/ba6c30b4-bb09-4c49-95b8-e64d50015047">

**Comment by dewenni** [comment]
An den LED´s würde ich es jetzt erstmal nicht festmachen.
Nach dem Flashen auf jeden fall einen Neustart machen. Dann sollte entweder ein WIFi Accesspoint mit dem Namen "ESP-Buderus-KM271" aufgemacht werden oder es verbindet sich mit deinem WLAN wenn du dies schon eingerichtet hast.

**Comment by stefangrosse** [comment]
Stimmt. Ich komme wieder auf die Einstellungen. Jetzt muss ich die Karte nur noch an Homeassistent anbinden.

**Comment by stefangrosse** [comment]
Welche GPIO Einstellungen sind die richtigen?

**Comment by dewenni** [comment]
für Home Assistant musst du eigentlich nur die MQTT Einstellungen vornehmen

<img width="528" alt="image" src="https://github.com/dewenni/ESP_Buderus_KM271/assets/46074831/43556c13-84a1-4753-a032-23fb8e8aa342">

Dann sollte es in HASS automatisch als MQTT Device angezeigt werden. Vorausgesetzt du hast auch in HASS die MQTT Integration aktiviert.

**Comment by stefangrosse** [comment]
Danke. Ich mußte die Karte erneut einmal reseten. Verbindung zum Mqtt funktioniert:

<img width="1181" alt="image" src="https://github.com/dewenni/ESP_Buderus_KM271/assets/16479653/a07be0b1-e69f-4b23-9200-ef294e833855">

Vielen Dank nochmal für diesen Mega Support!

**Comment by stefangrosse** [comment]
Die SetValue Commands z.B: 
command:    warm water: setpoint temperature
topic:      {"setvalue/ww_soll", setvalue/ww_setpoint"}
payload:    Resolution: 1 [°C] - Range: 30 ... 60 [°C]

Werden nicht über das Discovery automatisch in HASS zur Verfügung gestellt und müssen manuell erstellt werden, richtig?

**Comment by dewenni** [comment]
doch, die sollten auch vorhanden sein:

<img width="476" alt="image" src="https://github.com/dewenni/ESP_Buderus_KM271/assets/46074831/abac2233-edc3-47c6-b7f3-732b5486b2f2">

**Comment by stefangrosse** [comment]
Die Karte sendet keinen Ping mehr:
![image](https://github.com/dewenni/ESP_Buderus_KM271/assets/16479653/f70ca818-fc15-4f26-8b18-e98dcdc9b9f6)

Die Sensoren sind in HASS nicht mehr verfügbar. Über die Weboberfläche kann ich sie normal öffnen. Ist das normal oder muss ich die Karte wieder neu starten?

**Comment by dewenni** [comment]
Wenn die Weboberfläche noch funktioniert, dann kontrolliere doch mal ob auch noch MQTT Nachrichten verschickt werden.
Ich nutze dazu den http://mqtt-explorer.com
