### ISSUE TITLE
Offline every three days

### ISSUE THREAD

**Issue by dremeier** [dewenni/ESP_Buderus_KM271#107]
I have the problem that the interface is not accessible every three days. The two green LEDs on the right light up. After a reset everything is OK again.
What is needed for further debugging?

**Comment by blacksheepinc** [comment]
I have a similar issue, for me the MQTT might be the problem. 
I can still reach/ping the device however in Home assistant, it show unavailable, after restart everything is ok for a day or two.

**Comment by gtsy7** [comment]
I have a similar issue, for me the MQTT might be the problem.
I can still reach/ping the device however in Home assistant, it show unavailable, after restart everything is ok for a day or two.

**Comment by dewenni** [comment]
please be patient - I am working on a new version with a different implementation

**Comment by dewenni** [comment]
@blacksheepinc  @dremeier 
please try the new release v5.0.0
If there are still stability problems - please create a new issue or use the discussion
