### ISSUE TITLE
Die Weboberfäche kann nach begrenzen des Zuganges nicht mehr geöffnet werden

### ISSUE THREAD

**Issue by stefangrosse** [dewenni/ESP_Buderus_KM271#109]
Hi.
Nachdem ich den Zugang in den Einstellungen begrenzt habe, kann ich nicht mehr auf die Weboberfläche zugreifen:
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/ad5b0138-2792-4dd0-89ef-40312a5fadc0">

Im Mqqt Explorer sehe ich, das die Karte noch erreichbar ist:
<img width="597" alt="image" src="https://github.com/user-attachments/assets/db337520-5b94-43f5-9c30-45959268a624">

Auch kommt der Ping in HomeAssistent im Log an.

**Comment by dewenni** [comment]
Hi,

das Problem ist mir bekannt und ich habe das auch schon behoben. Ich versuche die nächsten Tage ein Update zu machen.
Das Update müsstest du dann zur Not nochmal per Kabel einspielen. Sorry!

Grüße
Sven

**Comment by DanMike** [comment]
Ich habe dasselbe Problem. Gibt es ein Telnet- oder MQTT-Kommando, um das wieder zu deaktivieren?

**Comment by dewenni** [comment]
Hallo,

ich habe das Problem  behoben und ein neues release dazu bereitgestellt.
Das Update müsstest du dann zur Not nochmal per Kabel einspielen. Sorry!

**Comment by DanMike** [comment]
Hallo @dewenni ,
danke für das Update, es läuft jetzt! 👍 

Ich hatte schon vorher per Kabel die 4.1.0 nochmal geflasht, damit ich wieder auf das Web UI komme.
Das Update jetzt auf 4.1.1 habe ich per OTA eingespielt. Beim ersten Versuch gab es bei 99% den Fehler "Update nicht erfolgreich". Habe es dann einfach nochmal ausgeführt und das hat geklappt.
Kein Sorry nötig, was Du hier machst ist ganz große Klasse! 🥇
