### ISSUE TITLE
Controlling the Circulation pump in Homeassistant

### ISSUE THREAD

**Issue by Eule01x** [dewenni/ESP_Buderus_KM271#110]
Today I got the time to test v4.1.1.
And what shall I say? I love the HA implementation, thanks for that! :)

But what I could not find is the option to control the circulation pump of warm water directly within HA.
Am I missing something?

**Comment by dewenni** [comment]
you are right, I will add it to my ToDo list

**Comment by dewenni** [comment]
@Eule01x 
included in actual release [v4.1.2](https://github.com/dewenni/ESP_Buderus_KM271/releases/tag/main)
please test

**Comment by DonCanDo** [comment]
Hey Leute,

ähm könnt ihr mir mal bitte noch die Werte erklären? An und Aus ist klar. Wofür stehen Werte 1-6?

Danköööö <3

**Comment by dewenni** [comment]
<img width="877" alt="image" src="https://github.com/user-attachments/assets/a596495d-4ac9-4bd0-9231-24a388793e0c">
