### ISSUE TITLE
WW Zirkulation Entität auf einmal weg

### ISSUE THREAD

**Issue by DonCanDo** [dewenni/ESP_Buderus_KM271#118]
Ich verstehe nicht, wieso heute auf einmal die Entität weg war und weg ist.

![Screenshot_20241024-215832.png](https://github.com/user-attachments/assets/7365503a-07b8-4bf6-bcfb-e5459f228644)

**Comment by DonCanDo** [comment]
Kann mir hier jemand weiter helfen?

**Comment by dewenni** [comment]
Ist das denn die neue Entität zum Bedienen oder noch die alte Entität als Sensor?

Die alte als Sensor ist ja weggefallen weil es ja jetzt eine Entität zur Bedienung gibt vom Typ "Option"

**Comment by DonCanDo** [comment]
Also die Einstellung geht. Aber da wird mir nicht angezeigt und getrackt wenn die Zirkulationspumpe läuft

**Comment by dewenni** [comment]
ist hier noch was offen?

**Comment by DonCanDo** [comment]
Kannst du zu machen die Entität ist wieder da

Grüße Steven
________________________________
