### ISSUE TITLE
Update not sucessfull!

### ISSUE THREAD

**Issue by gtsy7** [dewenni/ESP_Buderus_KM271#129]
![271](https://github.com/user-attachments/assets/efeb0827-b4c9-4ed2-911b-8cb3034bd3f8)

**Comment by dewenni** [comment]
The memory on a 4MB chip is now with Arduino V3 tight, but it should actually still fit (approx. 83% occupied)

- Have you tried it again?
- what kind of ESP do you use?
- if the OTA update is not possible, you can try to flash it with the new version

**Comment by gtsy7** [comment]
Buderus-KM217-WIFI | Rev: 0.0.5
the78mole | 2022-10-13
you can send me the version 0.7 of the printed circuit board I want to make a new one.

**Comment by gtsy7** [comment]
Will I have to buy it again?

**Comment by dewenni** [comment]
> you can send me the version 0.7 of the printed circuit board I want to make a new one.

I thought you asked about that. Then I didn't understand the question.

**Comment by gtsy7** [comment]
I already bought it, but I have an old version, I think that's why there are problems.

**Comment by gtsy7** [comment]
???

понедельник, 2 декабря 2024 г. пользователь Sven T. <
***@***.***> написал:
