### ISSUE TITLE
I can't find the "s_webui_texts" structure. 

### ISSUE THREAD

**Issue by vovanmm661905** [dewenni/ESP_Buderus_KM271#13]
Hi guys. 
I tried to rebuild the project for ESP8266. I can't find the s_webui_texts structure in the project. Please help.

**Comment by vovanmm661905** [comment]
Thank you already found. I had an old version of the source.

**Comment by dewenni** [comment]
@vovanmm661905 
just out of interest, are you running the project on an ESP8266?
