### ISSUE TITLE
watchdog

### ISSUE THREAD

**Issue by Franck78** [dewenni/ESP_Buderus_KM271#130]
Hi,

Apparently I have a problem since v4 (all). No real time to investigate it.

I test the board on a spare KM2107 that I have on the shelf. It means the KM have not any sensors and is displaying ERR blah blah blah missing sensor ok.

Have you tried running the board on this kind of installation ?

I say watchdog because it is the typical behavior. Restart every 5 or so seconds ;)

Franck

**Comment by dewenni** [comment]
no I haven´t such a installation. Only a pure ESP32 and the real heating system.
What is described as "restart reason" in the WebUI - System page?
Are WiFi and MQTT working? If not, I trigger a restart after 5 connection attempts.
Maybe this is actually the reason.
There is now also a V5.0.0 which I recommend using.

**Comment by dewenni** [comment]
https://github.com/dewenni/ESP_Buderus_KM271/blob/a9ce677a795b8a549cd5b595987ba541061714a6/src/mqtt.cpp#L183

This is a kind of safety function since the beginning, as mqtt is more or less mandatory.
But yes, I could also make that adjustable.

**Comment by Franck78** [comment]
constant rebooting prevents from doing anything.
-uploading another image
-disabling mqtt
and of course just monitoring ;)
