### ISSUE TITLE
Node-Red / InfluxDB / Grafana

### ISSUE THREAD

**Issue by samuelengelking** [dewenni/ESP_Buderus_KM271#21]
Hello,

you have done great work here! The WebUI is extremely helpful.

Could you also please share your configuration for Node-Red / InfluxDB / Grafana?

Thank you!

**Comment by dewenni** [comment]
Hi @samuelengelking 
sure I can share my grafana Dashboard and also the major node-red flows.
Please see attached json export files. You can import them in grafana and node-red.

If you have additional questions, feel free to ask.

[node-red.txt](https://github.com/dewenni/ESP_Buderus_KM271/files/11254979/node-red.txt)
[grafana.txt](https://github.com/dewenni/ESP_Buderus_KM271/files/11254980/grafana.txt)

**Please rename the files from** `.txt` **to** `.json*`
