### ISSUE TITLE
OpenHab Channel configuration

### ISSUE THREAD

**Issue by Extrme** [dewenni/ESP_Buderus_KM271#25]
Hi Sven, excellent work!

I use OpenHab as my smart home system. I created a simple parser that translates your params.txt file to a YAML file that can be used to configure MQTT things and their channels in OpenHab. 

If you think it would be helpful, I would be happy to contribute this parser and the YAML file to your repo.

Regards,
Thomas

**Comment by dewenni** [comment]
Hi Thomas,

Thanks, that sounds interesting. I am not familiar with OpenHab so far, but if it could be a nice Add-On, why not.
Maybe you can create a pull-request, than I can take a look on it and see how we could include it.
It should be also not a big thing for me to run OpenHab in docker to test it.
So let's see.

Sven
