### ISSUE TITLE
FRequest: MQTT: Make config values retained

### ISSUE THREAD

**Issue by DirkSchultze** [dewenni/ESP_Buderus_KM271#28]
Hi,

could you add a (switchable) option in settings to retain MQTT config messages?
Config messages are only sent on boot of the module or when changed so these messages should be retained on the mqtt broker.

Regards

Dirk

**Comment by dewenni** [comment]
Hi Dirk,

thanks you for that input. Sounds reasonable.  
I will implement this in the next release.

regards
Sven

**Comment by dewenni** [comment]
implemented in [Release v3.2.0](https://github.com/dewenni/ESP_Buderus_KM271/releases/tag/v3.2.0)
