### ISSUE TITLE
Passwort / Adminaccount

### ISSUE THREAD

**Issue by DM-LUKAD** [dewenni/ESP_Buderus_KM271#49]
Hallo, 
erst einmal vielen Dank für diese gute Arbeit!

Ich hätte gerne (vielleicht auch andere) ein Passwort als Schutz von Veränderung (Parameter/Heizung/ect.) .
Oder einen "Admin" der diese Konfig überhaupt anzeigen lässt.

Vielen Dank !

**Comment by dewenni** [comment]
Danke für den Input.
Das sollte grundsätzlich möglich sein.
Ich schaue es mir an.

**Comment by dewenni** [comment]
@DM-LUKAD : added in v3.3.0

**Comment by DM-LUKAD** [comment]
@dewenni: hey super - ill try this later !! thanks !!
