### ISSUE TITLE
Außentemperatur Anzeigefehler 

### ISSUE THREAD

**Issue by floschad** [dewenni/ESP_Buderus_KM271#65]
Hi,

unter 0°C wird die Außentemperatur falsch angezeigt, siehe Fotos. V3.2.4 Logamatic Version 3.15 Logamatic Modul 2
![Screenshot_20240119-064227](https://github.com/dewenni/ESP_Buderus_KM271/assets/142580885/9d8baf7c-9da3-4597-979f-c2be3d3f3f0b)
![PXL_20240118_210237273](https://github.com/dewenni/ESP_Buderus_KM271/assets/142580885/b8d45670-1e59-41e6-9494-030055e4335b)

**Comment by dewenni** [comment]
Danke für den Hinweis - das ist bereits bekannt und gefixed. #51
Ich habe es nur noch nicht geschafft ein neues Release zu erstellen da ich immer noch versuche zu verstehen warum so viele user Probleme mit der letzten Version haben (V3.2.4)
Bei dir scheint die aber ja sonst zu funktionieren, oder?
Welche Hardware hast du verbaut? das Board von Daniel oder ein normalen ESP mit der original KM271?

**Comment by floschad** [comment]
Ich habe das Modul von Daniel verbaut, funktioniert alles ohne Probleme.
Ich hatte vorher ESPeasy als ser2net Server mit Fhem (KM271-Modul) in Betrieb, ebenfalls ohne Probleme.
