### ISSUE TITLE
Sollwerte Heizkreise

### ISSUE THREAD

**Issue by floschad** [dewenni/ESP_Buderus_KM271#66]
Hi,

es wäre toll, wenn man auch den Sollwert der Heizkreise für Tag und Nacht einstellen könnte. Hier sind die Werte alle von Rudolf König zu finden: [(https://github.com/mhop/fhem-mirror/blob/master/fhem/contrib/km271.pl)](url)
Danach Raumsollwert.

**Comment by dewenni** [comment]
Hallo,

die FHEM Implementierung war zum Großteil auch meine Vorlage zu Umsetzung.
Das was du verlinkt hast sind aber alles nur Istwerte.
Auch die Raumsolltemperatur ist ein Istwert der gelesen wird.

Das habe ich auch schon implementiert
<img width="991" alt="image" src="https://github.com/dewenni/ESP_Buderus_KM271/assets/46074831/538a6f54-1a77-48ab-9074-2a764801f522">

Der Wert für den "Raumsollwert" kommt aber von einem Raumthermostat was ich nicht verbaut habe.
Den Wert dafür vorzugeben wurde hier schon mal diskutiert #44

**Comment by floschad** [comment]
Top, vielen Dank!
