### ISSUE TITLE
2105 LANG

### ISSUE THREAD

**Issue by Franck78** [dewenni/ESP_Buderus_KM271#68]
On the 2107, 5 languages are defined: DE,FR,IT,NL,PL

On the 2105, there is much more and sadly, not in the 2107 order

DE,
AMERICAN,
ENGLISH,
FR,
NL,
IT,
Espagnol,
Magyar,
and a lot of other from Turkey to Russia

**Comment by dewenni** [comment]
Hi, Thanks for the hint. Any idea how to deal with that?

**Comment by Franck78** [comment]
Remove the country code indication from display  !?

Maybe the software version can gives a hint v2.x => HM2105 v3.x => HM2107. 
And probably, some other diff will emerge.

Maybe a pool with owners, asking them software version and HM model.

Franck
