### ISSUE TITLE
See log from webserver

### ISSUE THREAD

**Issue by Franck78** [dewenni/ESP_Buderus_KM271#70]
To help debug or enhance the thing, it would be a good idea have a circular buffer in ram (20-100Ko?) where messages are logged (with a time stamp).

Then the content of the buffer is served from the webserber.

`http://192.168.1.44/log`

  and you simply get the buffer. No fancy css needed. Just text.

Also return a "404" to conform to basic http protocol.

**Comment by dewenni** [comment]
implemented in new release candidate #80

**Comment by dewenni** [comment]
implemented since [release 4.0.0](https://github.com/dewenni/ESP_Buderus_KM271/releases/tag/v4.0.0)
