### ISSUE TITLE
Alarm message configurable

### ISSUE THREAD

**Issue by markus-hi** [dewenni/ESP_Buderus_KM271#8]
Hi Sven,

with my oil heater control 2105 there are no useful output of alarm messages. Can you please implement a config option to disable the trasmit of any alarm messages? So that in config. h is a option like this:
`#define ALARM_MESSAGES`

Acutally the mssages flooding my mqtt Broker ;-)

Thanks!

**Comment by dewenni** [comment]
implemented with release [v1.3.4](https://github.com/dewenni/ESP_Buderus_KM271/releases/tag/v1.3.4)
