### ISSUE TITLE
ESP32 mit LAN Anschluß ?

### ISSUE THREAD

**Issue by Kenaschon** [dewenni/ESP_Buderus_KM271#81]
Hallo zusammen,

gibt es eine Möglichkeit, das alles auch per Lan-Kabel zu realisieren?

Ich habe die 3.3.1 drauf. Leider verliert sie immer noch regelmäßig die Wlan Verbindung. Trotz Wlan-Repeater im Keller.

Gibt keinen ESP32 mit Lan Anschluß auf dem man die Software aufspielen kann?

Grüße
Manfred

**Comment by dewenni** [comment]
Hallo Manfred,

es gibt spezielle ESP32 Board mit LAN Anschluss, aber es gibt auch Erweiterungsmodule die man per SPI-Bus an einen ESP32 anbinden kann.
Ich habe mir mal spontan so ein Erweiterungsmodul bestellt und werde die Implementierung mal testen.
Das könnte generell ganz interessant sein. Mein Empfang ist im Keller auch nicht der Beste und LAN wäre kein Problem.
Ich teste das mal und melde mich.

Grüße Sven

**Comment by Kenaschon** [comment]
Vielen Dank für die schnelle Reaktion.

**Comment by the78mole** [comment]
Hi all,

just want to join the discussion as the HW developer of the KM271-WiFi :-P 
The KM271-WiFi-Board gives access to the SPI signals on the extension header J7, as depicted in the following images/screenshots.
![image](https://github.com/dewenni/ESP_Buderus_KM271/assets/7723396/b1f80c75-352f-4c5e-8823-67677394b375)
![image](https://github.com/dewenni/ESP_Buderus_KM271/assets/7723396/89606d72-b70c-4f76-bb09-295721c67c6a)
![image](https://github.com/dewenni/ESP_Buderus_KM271/assets/7723396/d425accc-9e96-45d9-8bae-2d36b35692d6)

If they do not collide with other stuff (r.g. internal SPI-Flash), you could easily attach one of the various Ethernet-SPI controllers to it (e.g. the [LAN8720](https://www.roboter-bausatz.de/p/lan8720-netzwerkmodul-lan-tcp-ip-ethernet)) and use the [arduino ESP-example](https://github.com/espressif/arduino-esp32/tree/master/libraries/Ethernet/examples/ETH_LAN8720) with it.

If this works, I would tend to design some "official" extension for the KM271-WiFi.

Regards,
Daniel

**Comment by Kenaschon** [comment]
Englisch - Deutsch - Englisch - Deutsch. Kann ich verstehen.

Ich verstehe auch, das github international sein soll, aber in diesem Fall stelle ich mir immer die Frage, wie viele haben im Ausland eine Buderus Öl-Heizung?

**Comment by the78mole** [comment]
Hi Kenaschon,

tatsächlich verschicke ich ca. 15-20% an Nutzer im Ausland, überwiegend aus der EU (Rumänien, Ungarn, Polen, Litauen,,...), aber auch einige z.B. in die USA und die Ukraine (vor 2022). Ich hab mir diese Frage vorher auch gestellt und war sehr überrascht, wo Buderus überall seine Kessel stehen hat. Besonders außerhalb der EU ist das ziemlich nervig, da man dann den ganzen Zoll-Kram ausfüllen muss.

Grüße,
Daniel

**Comment by dewenni** [comment]
Hi,

ich habe gestern spontan mal einen [W5500](https://www.roboter-bausatz.de/p/w5500-mini-netzwerkmodul-lan-tcp-ip-ethernet) bestellt. Der macht einen guten Eindruck und kann per SPI angebunden werden.
In der Bauform ist er auch sehr kompakt und könnte ggf. dann zukünftig auf das Board mit aufgesteckt werden?

Ich teste das mal in der Software und Berichte.

Grüße Sven

PS: bezüglich englisch. Es gibt scheinbar mehr internationale Interessenten als man denkt. Daniel hat auch schon einige Boards ins Ausland verkauft. Hätte ich anfangs auch nicht gedacht.

**Comment by the78mole** [comment]
Hi @dewenni,

tatsächlcih scheint der LAN8720 selbst kein SPI zu haben, der W550 allerdings schon.

Bin gespannt, was Du berichtest.

Grüße,
Daniel

**Comment by Kenaschon** [comment]
Ich dachte das so etwas geht.

https://www.roboter-bausatz.de/p/wt32-eth01-esp32-modul-mit-ethernet-bluetooth-wifi

**Comment by JieffeEl** [comment]
@Kenaschon Buderus is also sold in Belgium where, despite German being one of the three national languages, almost nobody speaks it :) I never learned it at school, whereas French (my maternal language) and Dutch are mandatory ...  Also, Buderus is (was?) sold under the label Bosch abroad.

@the78mole @dewenni  I once bought a LAN8720 module but it seems to need an awful lot of pins to function, as well as a few hardware modifications. The W5500 is certainly a wiser solution in this regard. In the past, I successfully used ENC28J60 modules with Arduinos and ESP8266s but that chip relies a lot on the microprocessor for the network protocols, contrary to the W5*00 that does most of the work internally.

**Comment by the78mole** [comment]
Hi @JieffeEl, @Kenaschon 

@JieffeEl  the LAN8720 has a default RMI, which has some, but not awfully lot signals. The ESP32 could also handle this, but it needs to be connected to certain pins, which are not routed to a pin header on my board. SPI-to-Ethernet is simply the only solution, my board can be extended with.

@Kenaschon if you want to design your own Buderus KM271, you are free to do so 😜, but the board you suggested does not fit on my board and simply makes no sense to be added, too, since mine already has an ESP32 populated. 😅

Regards,
Daniel

**Comment by dewenni** [comment]
As is so often the case, it's not as easy as you think. The W5500 does not work out of the box with the "standard" ESPAsync web server that I am using. There are already several issues here.
However, there are examples where this was generally done with a web server. But apparently always with various adjustments.

this example [WebServer_ESP32_W5500](https://github.com/khoih-prog/WebServer_ESP32_W5500) works, but I have to check how I can adapt this to my project.

**Comment by the78mole** [comment]
@dewenni Autsch! Klingt nach unschöner Arbeit und nach einem Haufen KB Speicher... Soweit ich weiß ist da nicht mehr viel Platz übrig, oder?

**Comment by dewenni** [comment]
ja, sieht leider nicht so aus, als könne man das einfach parallel zum Standard WiFi und Standard WebServer betreiben.

Wenn ich es aber [hier](https://github.com/espressif/arduino-esp32/issues/8605#issuecomment-2034383284) richtig deute, dann könnte sich das ab Arduino 3.0 bessern.

Wann das kommt, ist mir aber nicht bekannt. Wenn man [hier](https://github.com/espressif/arduino-esp32/milestone/4) schaut, könnte es aber bald verfügbar sein.

**Comment by the78mole** [comment]
Hm, klingt vielversprechend... Somit bleibt mir ja noch etwas Zeit für die Umsetzung der HW 🤣

**Comment by dewenni** [comment]
So, ich habe es mal grundsätzlich mit Arduino 3.0 (alpha) in meinem Projekt am laufen.
Ich musste aber auch ein paar Dinge deaktivieren und auch in der AsyncTCP provisorisch IPV6 deaktivieren.
Auch parallel zum WiFi funktioniert es noch nicht. Zumindest nicht mit den bisherigen WiFi Funktionen. Die muss man ggf. auch durch neue Funktionen ersetzen. die bisherige OneWire Funktion ist auch nicht mehr kompatibel.
Also irgendwie wird das schon funktionieren, aber ganz so einfach ist es nicht.
Ich warte mal auf das release von Arduino 3 und dann werde ich mich damit nochmal weiter beschäftigen.

**Comment by dewenni** [comment]
@the78mole 
konkret habe ich dieses [W5500 Modul](https://www.az-delivery.de/products/w5500-ethernet-netzwerk-internet-modul-fuer-arduino) gekauft. Das müsste man dann mit einem Kabel anschließen und ggf. nochmal in ein extra Gehäuse packen.

<img width="1205" alt="image" src="https://github.com/dewenni/ESP_Buderus_KM271/assets/46074831/b11e5031-8ad2-4833-ae46-ecdf46bdc468">


Als Header für dein Board wäre aber [diese Bauform](https://www.roboter-bausatz.de/p/w5500-mini-netzwerkmodul-lan-tcp-ip-ethernet?srsltid=AfmBOopXO3m2K_GUOOebsRd9pD0J_G6smNyHzLr0dfZDWPB8LJPnvJZ5iMg) vielleicht interessanter. 

![](https://www.roboter-bausatz.de/media/image/04/80/6c/RBS16003.jpg)

Das Teil könnte man ja ggf. direkt auf dein Board aufstecken wenn du die Stiftleisten entsprechend vorsiehst.

Man benötigt aber auch fast alle Pins (6+2) in der Software:

- (01) ETH_PHY_CS
- (02) ETH_PHY_IRQ
- (03) ETH_PHY_RST
- (04) ETH_SPI_SCK
- (05) ETH_SPI_MISO
- (06) ETH_SPI_MOSI
- (07) VCC
- (08) GND

Soweit ich das bisher verstanden habe, könnte man das WiFi sogar parallel zum Ethernet betreiben.
Aber das muss man dann mal ausprobieren. Aktuell habe ich mein Projekt mit Arduino 3 und dem Ethernet provisorisch am laufen. Dafür bekomme ich in Arduino 3 das WiFi generell nicht zum laufen. Auch nicht in einem neuen leeren Testprojekt.
Da passt scheinbar irgendwas mit meinem Platformio Setup nicht. Aber ich bleibe da mal dran und berichte wenn ich beides am laufen habe.

**Comment by the78mole** [comment]
Hi @dewenni 

in ESPhome sind folgende Pins angegeben:

    # Example configuration entry for SPI chips
    ethernet:
      type: W5500
      clk_pin: GPIO19
      mosi_pin: GPIO21
      miso_pin: GPIO23
      cs_pin: GPIO18
      interrupt_pin: GPIO36
      reset_pin: GPIO22

Sieht fast so aus, als könnte man das halbwegs frei konfigurieren:
SPI based chips do not use [SPI Bus](https://esphome.io/components/spi). This means that SPI pins can’t be shared with other devices.

Allerdings steht auch auf der ESPhome-Seite: This component and the Wi-Fi component may not be used simultaneously, even if both are physically available.

Ich werde einfach mal ein sauberes Board entwerfen und das dann testen. Jetzt müssen erst mal die 100 neuen Module endlich bei mir ankommen. Die hängen schon die ganze Woche im deutschen Zoll fest und der meldet sich einfach nicht :-(

Grüße,
Daniel

**Comment by dewenni** [comment]
kurzes update: In einem einfachen Testprojekt in der Arduino IDE, läuft auch WiFi mit dem W5500 parallel.
Ich habe einen kleinen Webserver in dem Projekt hinterlegt und den kann ich sowohl über die WiFi IP und auch über die LAN IP erreichen. Das wäre also sehr komfortabel.

**Comment by the78mole** [comment]
Sag mal @dewenni ,

könntest Du spaßeshalber mal die Stromaufnahme und die Stromspitzen des gesamten Boards messen?
- nur Ethernet
- nur WLAN (dürfte bei WLAN-Aktivität ca. 170 mA sein)
- WLAN + Ethernet

Am einfachsten geht das, wenn man ein USB-Power-Messgerät hat und das Board über den USB versorgt.

Aktuell tippe ich schwer darauf, dass es mit Ethernet deutlich stromsparender sein sollte und geschätzt dann weniger als 100 mA in der Spitze zieht.

Das wäre dann eine gute Alternative für die wenigen Leute (3-5%), wo die Spannungsversorgung der Buderus-Steuerung ein wenig schwachbrüstig geraten ist und das Board manchmal einen Power-On-Reset ausführt.

Grüße,
Daniel

**Comment by akno2205** [comment]
Hallo Daniel, ich mir diese Woche Dein KM271 Board zugelegt und bin sehr begeistert. Leider gehöre auch ich zu den Menschen mit schlechtem Wlan im Keller wo sich die Heizung befindet. Da ich sehr gute Erfahrungen mit ESP32-WROOM-32U mit externer Antenne gemacht habe. Habe ich mich gefragt, ob man dies nicht als Option nutzen könnte. Somit wäre es möglich einen besseren Empfang zu bekommen. Diese wäre nicht so umständlich, wie einen Lan-Port zu verbauen. Man könnte nur den ESP tausche, sofern dieser den Anforderungen entspricht.
Gruß Andy

**Comment by the78mole** [comment]
Hi Andy,

habe Dir ja schon per Email geantwortet. Für andere, die das hier lesen, noch mal kurz die Passage zum ESP32 mit externer Antenne:

Grundsätzlich ist es natürlich möglich und ich habe mir das auch bereits überlegt. Allerdings hätte ich dann zwei Varianten des Moduls, was die Bevorratung dann ganz schnell teurer für mich macht. Auch der Skaleneffekt ist dann natürlich nicht mehr so groß, wenn ich nicht mehr die gleiche Menge einer Variante bestelle. Aktuell habe ich eine Variante und löte die Optionen dann nach Nutzerwunsch auf. Da das nur "grobe" THT-Stecker sind, geht das recht flott. Wenn ich das mit dem ESP-Modul ebenfalls so machen wollte, dann müsste ich, je nach Nutzerwunsch, ein anderes Modul per Hand auflöten. Das ist mir viel zu aufwendig. 

Nun gäbe es noch zwei Möglichkeiten: Entweder ein ESP-Modul umlöten oder ein blankes PCB komplett neu bestücken. Ersteres ist schwierig, selbst mit Heißluft-Lötkolben. Für Letzteres habe ich gar nicht alle Bauteile da (z.B. die Levelshifter oder die größeren ELKOs).

Grüße,
Daniel

**Comment by dewenni** [comment]
@the78mole @Kenaschon @akno2205 @JieffeEl 

Ich habe nun im aktuellen Release v5.0.0 die Unterstützung für einen Ethernet Abschluss implementiert.
Ausgelegt ist die Implementierung für ein W5500 Board. Das kann man einzeln kaufen und sowohl an einem normalen ESP32 als auch an dem Board von Daniel anschließen.
Doku findet ihr in der Readme.md
Das ganze läuft bei mir an einem Board v0.0.6 zuverlässig.
Wichtig ist nur, das das Kabel zwischen Board und W5500 so kurz wie möglich ist (ca 10cm). Ein längeres Kabel hat bei mir Probleme gemacht.

**Comment by Kenaschon** [comment]
Hallo Dewenni,

vielen Dank für die tolle Arbeit. Habe mir direkt ein W5500 bestellt. Melde mich wenn es da ist.

Grüße
Manfred

**Comment by dewenni** [comment]
@Kenaschon und alle anderen Interessenten
@the78mole hat hierzu auch schon was geplant - Ihr könnt euch zumindest schon mal auf die Warteliste setzten:
https://www.tindie.com/products/the78mole/km271-wifi-ethernet-extension/

![image](https://github.com/user-attachments/assets/4ba049bb-a5da-4c45-87e0-62fc5fa67c19)

**Comment by Kenaschon** [comment]
Nette Idee.

Ist auch ein "nur" Board km271 mit Netzwerkanschluss geplant?

**Comment by the78mole** [comment]
Hi Kenaschon,

> Ist auch ein "nur" Board km271 mit Netzwerkanschluss geplant?

Meinst Du, direkt auf der Einsteckkarte ein Ethernet? Nein, eher nicht. Die Resonanz auf die Ethernet-Extension ist weit hinter den Erwartungen, da rentiert sich ein KM271-Ethernet nicht bzw. ist den Aufwand nciht wert. Ich werde ohnehin nicht mehr ewig Support machen können. Die olle Buderus-Heizung fliegt in den nächsten 1-2 Jahren raus und dann wird es schwierig mit dem Real-World-Testen. Da kann ich mir die Buderus nur noch neben den Schreibtisch stellen und schauen, ob die Kommunikation grundlegend funktioniert...

Grüße,
Daniel

**Comment by Kenaschon** [comment]
Bevor ich es direkt alles verbinde, ist das so ok?

![D1-Mini-ESP32-back-1](https://github.com/user-attachments/assets/2494d106-9198-408f-bed1-a57cb4cf93f8)

**Comment by dewenni** [comment]
Ich hatte zuletzt folgende Belegung genutzt:
ESP32-Mini
|  | GPIO |
|------|----|
| CLK   | 18 |
| MOSI | 23 |
| MISO | 19 |
| CS     | 5   |
| INT    | 16 |
| RST   | 17 |

**Comment by Kenaschon** [comment]
"Wichtig ist nur, das das Kabel zwischen Board und W5500 so kurz wie möglich ist (ca 10cm). Ein längeres Kabel hat bei mir Probleme gemacht."

Ich habe die Kabel durch einen Ferrit-Kern gelegt. Danach war alles ohne Störungen und Probleme.

Grüße
Manfred
