### ISSUE TITLE
Unterbrechung nach einer gewissen Zeit

### ISSUE THREAD

**Issue by Kenaschon** [dewenni/ESP_Buderus_KM271#84]
Hallo,

ist es normal, das nach einer gewissen Zeit (ca. 1 Stunde) immer diese Anzeige kommt?

![unterbro](https://github.com/dewenni/ESP_Buderus_KM271/assets/47242804/758e1b79-1591-4695-9bae-6113b3da1799)

**Comment by Kenaschon** [comment]
Das passiert auch, wenn der Browser offen ist und sonst nichts am Rechner gemacht wird. Ruhezustand habe ich nicht am Rechner.

**Comment by dewenni** [comment]
ich habe im aktuellen [Release v4.0.2](https://github.com/dewenni/ESP_Buderus_KM271/releases/tag/v4.0.2) ein re-connect eingebaut. Kannst du mal testen

**Comment by Kenaschon** [comment]
Habe das Update eingespielt - werde berichten. Vielen Dank für die schnelle Umsetzung.

**Comment by Kenaschon** [comment]
Es scheint zu funktionieren. Danke dafür.
