### ISSUE TITLE
Literanzeige virtueller Ölzähler

### ISSUE THREAD

**Issue by Kenaschon** [dewenni/ESP_Buderus_KM271#85]
Kann es sein, das die Literanzeige bei dem virtuellen Ölzähler nicht stimmt?

Ich glaube das das Komma (Punkt) dort nicht hingehört. Wenn ich den Verbrauch durch die Betriebszeit des Brenners aufzeichne komme ich z.B. auf 3 Liter. In der selben Zeit zeigt mir der virtuelle Ölzähler einen um 0,03 Liter erhöhten Wert.

**Comment by dewenni** [comment]
ja, ich habe hier versehentlich auch durch 100 geteilt wie bei dem Hardware Ölzähler.
Das ist aber falsch. Ich habe es korrigiert und mache am Wochenende nochmal ein Release.
