### ISSUE TITLE
Webserver keeps freezing after plugged into Heating board

### ISSUE THREAD

**Issue by Kev0123** [dewenni/ESP_Buderus_KM271#95]
after an [issue configureing the wifi](https://github.com/dewenni/ESP_Buderus_KM271/issues/94), the board will freeze if plugged into the buderus heating board. The version is 0.0.8

**Comment by the78mole** [comment]
Did you configure the GPIOs as mentioned in this discussion?
https://github.com/dewenni/ESP_Buderus_KM271/discussions/86

**Comment by Kev0123** [comment]
Setting the GPIO did the trick ;-) Sometimes I am blind :-D
