### ISSUE TITLE
Not booting on powerup / LED status

### ISSUE THREAD

**Issue by Kev0123** [dewenni/ESP_Buderus_KM271#99]
After cutting the power to the Buderus the board won't come on without a push of the reset button. Is this intended?

Where is the status of the LEDs documented? The 2nd is orange, 3rd is blinking green and last one is constant on.

**Comment by Kev0123** [comment]
As I see right now the webserver and Wifi keeps crashing as well...

**Comment by dewenni** [comment]
Hi @Kev0123 
the LED status depends on your settings and your Hardware. You can configure the LED´s in the GPIO Settings
<img width="757" alt="image" src="https://github.com/dewenni/ESP_Buderus_KM271/assets/46074831/150fed74-7b5c-4965-842a-a45c8d5c7cf0">

That the "software" crashes is something that is hard to analyze for me, because I haven't seen this so far with the 4.x Software. My board has now been working for 13 days.
<img width="943" alt="image" src="https://github.com/dewenni/ESP_Buderus_KM271/assets/46074831/ec193d08-da3b-4922-b885-77fe837516fc">

**Comment by the78mole** [comment]
Try supplying it through USB (don't forget to replace the one PWR_SEL Jumper). If it stops crashing, than you are one of the few Buderus owners with a weak/crappy internal power supply. See my [YouTube-Video](https://www.youtube.com/watch?v=h_pQlpXaQ1I&t=810s) if not sure about the Jumpers.

**Comment by dewenni** [comment]
@Kev0123 any news?

**Comment by Kev0123** [comment]
Sry for the late response.

After re-plugging the device into the logamatic port, the booting works fine now. I just wanted to watch if the crashed will occure after some time. 
The random reboot seems to be fixed with the latest version and/or because of reinserting. Don't know if its a co-incident or just because of the previous bad connection between the board and the logamatic.

For now everything is working fine.

I couldn't figure out how to aggregate the infos from of the gerber files and the pinout to see which LED does what, so if anyone can give a basic overview whats the "stock" config if GPIO is set to the latest version ( thing its <0.0.6 or so labeld) would be great. Otherwise the topic can be closed.

Thanks for the support!

**Comment by the78mole** [comment]
Hi Kev,

sorry for not replying, was on vacations with family for some days...

You could do it the hard way using gerber files, but you could also use the interactive BOM for easy access to your infromation. If you have the 0.0.5 e.g., use this link:
https://htmlpreview.github.io/?https://github.com/the78mole/km271-wifi/blob/main/KM217-WiFi/bom/ibom%200.0.5.html

Here you can select the appropriate net and see it highlighted in total:
![image](https://github.com/dewenni/ESP_Buderus_KM271/assets/7723396/459bd16e-be5b-4125-8f3b-0ca15b6f132c)

You can replace the URL with any from here to get the iBOM of the different versions, from that file list:
https://github.com/the78mole/km271-wifi/tree/main/KM217-WiFi/bom

Now it should be quite straight forward to track down the GPIOs together with the schematics, which could be found here in PDF format:
https://github.com/the78mole/km271-wifi/tree/main/KM217-WiFi/Export

In dewennis firmware, you can assign different functions to the LEDs' GPIOs.

Hope this help :-)

Regards,
Daniel

**Comment by dewenni** [comment]
maybe I can add this information in the webui settings as well.

**Comment by dewenni** [comment]
@Kev0123 @the78mole 
I have added some information dialog to the settings page - will be available with the next release
<img width="730" alt="image" src="https://github.com/dewenni/ESP_Buderus_KM271/assets/46074831/f3491153-ff4d-4821-8720-46531aafef30">

**Comment by mutex1980** [comment]
I have Rev 0.0.8 and the Board does not (at least in 9 of 10 cases) boot even when USB powered. 
Inside the Logamatic it never booted without pressing reset.

Jumpers must be correct as booting works after pressing reset.

https://github.com/the78mole/km271-wifi/issues/6

**Comment by dewenni** [comment]
I close this topic here, because I think it is nor related to the software.
Go ahead here: https://github.com/the78mole/km271-wifi/issues/6
